AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String

  Domain:
    Type: String

  HostedZoneId:
    Type: String

  AcmCertificateArn:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3OriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "for S3 access"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: BucketPolicyForCloudFront
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              Fn::Sub: "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              AWS:
                - Fn::Sub: "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${S3OriginAccessIdentity}"

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName:
              Fn::GetAtt: S3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Sub: origin-access-identity/cloudfront/${S3OriginAccessIdentity}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: https-only
          ForwardedValues:
            QueryString: false
        DefaultRootObject: index.html
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn:
            Ref: AcmCertificateArn
        Aliases:
          - Ref: Domain

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        Ref: Domain
      Type: A
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - CloudFront
            - DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId:
        Ref: HostedZoneId
